---
- name: install epel
  yum:
    name:
    - epel-release

- name: install packages
  yum:
    name:
      - libselinux-python

      - screen

      - redhat-lsb-core
      - yum-utils
      - sudo
      - net-tools
      - bind-utils
      - deltarpm
      - lsof
      - tree
      - nmap
    state: latest

- name: copy .screenrc
  copy: src=screenrc dest=/root/.screenrc owner=root group=root mode=0600
- name: edit bashrc, vimrc
  shell: echo "alias vi='vim'" >> /root/.bashrc && echo "colorscheme desert" >> /etc/vimrc

- name: set timezone to Asia/Novosibirsk
  timezone:
    name: Asia/Novosibirsk

- name: add mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  with_items:
  - { name: fileServer, ip: 192.168.11.150 }
  - { name: fileClient, ip: 192.168.11.151 }

- name: put SELinux in permissive mode
  selinux:
    policy: targeted
    state: permissive
